baseURL: "https://carlguo508.github.io/"
title: "Carl"
theme: "PaperMod"
pagination:
  pagerSize: 10

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false

  homeInfoParams:
    Title: "Hi, I'm Carl"
    Content: "Welcome to my blog"

  socialIcons:
    - name: github
      url: "https://github.com/carlguo508"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - name: Posts
      url: /posts/
      weight: 1
    - name: Tags
      url: /tags/
      weight: 2
    - name: Archives
      url: /archives/
      weight: 3
    - name: About
      url: /about/
      weight: 4

outputs:
  home:
    - HTML
    - RSS
    - JSON

taxonomies:
  tag: tags
